---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple
spec:
  replicas: 1
  selector:
    matchLabels:
      app: simple
      version: v1
  template:
    metadata:
      labels:
        app: simple
        version: v1
    spec:
      serviceAccountName: simple
      containers:
      - image: chuy08/simple:0.1.2
        imagePullPolicy: Always
        name: simple
        ports:
        - containerPort: 80
        args:
          - server
