apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: public-gateway
spec:
  hosts:
  - "*"
  gateways:
  - public-gateway
  http:
  - match:
    - uri:
        exact: /_command/
    route:
    - destination:
        host: {{ .Chart.Name }}
        port:
          number: 1323