---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-private
spec:
  hosts:
    - private.mymco.local
  gateways:
    - simple-gateway
  http:
  - match:
    - uri:
        prefix: /_command/
    route:
    - destination:
        host: simple
        port:
          number: 8000
