---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: simple-public
spec:
  hosts:
    - public.mymco.local
  gateways:
    - simple-gateway
  http:
  - match:
    - uri:
        prefix: "/_command/status"
    route:
    - destination:
        host: simple
        port:
          number: 8888
  - match:
    - uri:
        prefix: /_command/
    route:
    - destination:
        host: simple
        port:
          number: 8000
